openapi: 3.2.0
info:
  title: Admin - Voice Comm Manager Job Details API
  description: 'The Voice provider APIs are used to manage information about voice specific elements and different voice related entities e.g. Phone numbers.


    Voice Services will support multiple ways to provision voice providers

    1. Programmatic Interface (Rest APIs)

    2. User Interface'
  contact:
    name: Avaya API Team
    url: https://developers.avayacloud.com/onecloud-ccaas
    email: apiteam@avaya.com
  license:
    name: Avaya Software Development Kit (SDK) Software License Terms
    url: http://support.avaya.com/css/P8/documents/101038288
  version: 1.0.2
servers:
- url: '{protocol}://{server}{basePath}'
  description: Open API
  variables:
    protocol:
      enum:
      - https
      default: https
    server:
      default: HOST-REGION.api.avayacloud.com
    basePath:
      default: /api/admin/voice/v1
security:
- {}
- BearerAuth: []
  AppKey: []
tags:
- name: Comm Manager Job Details
  description: This API is used to get details of list of jobs or a single job for a specific Communication Manager. These API are expected to be called by an account administrator.
paths:
  /accounts/{accountId}/communication-managers/{communicationManagerId}/jobs/{jobId}:
    get:
      tags:
      - Comm Manager Job Details
      summary: Get a single job
      description: '**This API requires the Account Administrator role.**


        Gets a single job by its job id.'
      operationId: getJob
      parameters:
      - $ref: '#/components/parameters/accountId'
      - $ref: '#/components/parameters/communicationManagerId'
      - $ref: '#/components/parameters/jobId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
              examples:
                default:
                  $ref: '#/components/examples/JobResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /accounts/{accountId}/communication-managers/{communicationManagerId}/jobs/{jobId}:details:
    get:
      tags:
      - Comm Manager Job Details
      summary: Get details of a single job
      description: '**This API requires the Account Administrator role.**


        Gets details of a single job by its job id.'
      operationId: getJobDetails
      parameters:
      - $ref: '#/components/parameters/accountId'
      - $ref: '#/components/parameters/communicationManagerId'
      - $ref: '#/components/parameters/jobId'
      - name: entityType
        in: query
        description: The optional entity type to query
        required: false
        schema:
          type: string
          enum:
          - AGENT
          - EXTENSION
          - REASONCODE_AUX
          - SYSTEM_PARAMETER_FEATURES
          example: AGENT
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDetails'
              examples:
                default:
                  $ref: '#/components/examples/JobDetailsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /accounts/{accountId}/communication-managers/{communicationManagerId}/jobs/{jobId}:entity-details:
    get:
      tags:
      - Comm Manager Job Details
      summary: Get entity details of a job
      description: '**This API requires the Account Administrator role.**


        Gets details of a sync entity by its job id.'
      operationId: getEntityDetails
      parameters:
      - $ref: '#/components/parameters/accountId'
      - $ref: '#/components/parameters/communicationManagerId'
      - $ref: '#/components/parameters/jobId'
      - name: entityType
        in: query
        description: The optional entity type to query
        required: true
        schema:
          type: string
          enum:
          - AGENT
          - EXTENSION
          - REASONCODE_AUX
          - SYSTEM_PARAMETER_FEATURES
          example: AGENT
      - name: statusCode
        in: query
        description: The optional job status code to query
        required: false
        schema:
          type: string
          enum:
          - IN_PROGRESS
          - COMPLETED
          - FAILED
          - CREATED
          - UPDATED
          - DELETED
          - CREATE_IN_PROGRESS
          - UPDATE_IN_PROGRESS
          - DELETE_IN_PROGRESS
          - NEEDS_ACTION
          example: COMPLETED
      - name: filter
        in: query
        required: false
        description: "Specifies details of a row filter.\n The possible fields that can be filtered on are:\n  * Name\n  * Number\n  * StatusCode\nField Names are case-senstive (should be written as it is in description).\nThe allowed format:\n  - Begins with the column name to be filtered, followed by a colon will be used to find out word that contains given value.\n"
        schema:
          type: string
          maxLength: 255
        examples:
          contains:
            description: Example of filtering based on an contains string.
            value: Name:dummyName
      - $ref: '#/components/parameters/pageNumber'
      - name: pageSize
        in: query
        description: The maximum number of results per page. Default value is 10, max value is 100.
        required: false
        schema:
          type: integer
          format: int32
          example: 10
          default: 10
          minimum: 1
          maximum: 100
      - name: orderBy
        in: query
        required: false
        description: 'Specifies how response data should be sorted. createdAt and updatedAt are valid options.

          Field Names are case-senstive (should be written as it is in description).

          To specify descending order, a suffix " desc" should be added. For example, "createdAt" for ascending or "createdAt desc" for descending".

          The default sorting order is createdAt ascending.

          '
        schema:
          type: string
          default: createdAt desc
          maxLength: 255
        examples:
          orderByCreatedAtInAscendingOrder:
            value: createdAt
            summary: sort data based on createdAt in ascending order
          orderByCreatedAtInDescendingOrder:
            value: createdAt desc
            summary: sort data based on createdAt in descending order
          orderByUpdatedAtInAscendingOrder:
            value: updatedAt
            summary: sort data based on updatedAt in ascending order
          orderByUpdatedAtInDescendingOrder:
            value: updatedAt desc
            summary: sort data based on updatedAt in descending order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncEntityDetailsPage'
              examples:
                default:
                  $ref: '#/components/examples/SyncEntityDetailsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /accounts/{accountId}/communication-managers/{communicationManagerId}/jobs:
    get:
      tags:
      - Comm Manager Job Details
      summary: Lists all the jobs
      description: '**This API requires the Account Administrator role.**


        Lists all the jobs for the specified Communication Manager.'
      operationId: listJobs
      parameters:
      - $ref: '#/components/parameters/accountId'
      - $ref: '#/components/parameters/communicationManagerId'
      - name: name
        in: query
        description: "The optional name of the job to query.\nThe allowed format:\n  - Begins with the column name to be filtered, followed by a colon, then:\n      - Either an exact string to match, or\n      - A string expression including the * wildcard character\n        - :{PREFIX}* will be used to find out word start with.\n        - :*{POSTFIX} will be used to find out word end with\n        - : will be used to match exact word\n - Begin with column name to be filtered, followed by a = operator. (this will be used to match exact string)\n"
        required: false
        schema:
          type: string
          minLength: 1
          maxLength: 255
        examples:
          exact:
            description: Example of filtering based on an exact string.
            value: name=FullSync_SYNC_Sat Mar 18 16:20:46 GMT 2023
          prefix:
            description: Example of filtering based on a prefix string.
            value: name:FullSync_SYNC_Sat*
          postfix:
            description: Example of filtering based on a postfix string.
            value: name:*GMT 2024
      - name: statusCode
        in: query
        description: The optional job status code to query
        required: false
        schema:
          type: string
          enum:
          - QUEUED
          - IN_PROGRESS
          - COMPLETED
          - TIMEOUT_FAILED
          - FAILED
          - NEEDS_ACTION
          example: FAILED
      - name: type
        in: query
        description: The optional type of job to query
        required: false
        schema:
          type: string
          enum:
          - SYNC
          - INCREMENTAL_SYNC
          example: SYNC
      - $ref: '#/components/parameters/pageNumber'
      - name: pageSize
        in: query
        description: The maximum number of results per page. Default value is 10, max value is 100.
        required: false
        schema:
          type: integer
          format: int32
          example: 10
          default: 10
          minimum: 1
          maximum: 100
      - name: orderBy
        in: query
        required: false
        description: 'Specifies how response data should be sorted. name, type, statusCode, createdAt and updatedAt are valid options.

          Field Names are case-senstive (should be written as it is in description).

          To specify descending order, a suffix " desc" should be added. For example, "name" for ascending or "name desc" for descending".

          The default sorting order is name ascending.

          '
        schema:
          type: string
          default: createdAt desc
          maxLength: 255
        examples:
          orderByNameInAscendingOrder:
            value: name
            summary: sort data based on name in ascending order
          orderByNameInDescendingOrder:
            value: name desc
            summary: sort data based on name in descending order
          orderByTypeInAscendingOrder:
            value: type
            summary: sort data based on type in ascending order
          orderByTypeInDescendingOrder:
            value: type desc
            summary: sort data based on type in descending order
          orderByStatusCodeInAscendingOrder:
            value: statusCode
            summary: sort data based on statusCode in ascending order
          orderByStatusCodeInDescendingOrder:
            value: statusCode desc
            summary: sort data based on statusCode in descending order
          orderByCreatedAtInAscendingOrder:
            value: createdAt
            summary: sort data based on createdAt in ascending order
          orderByCreatedAtInDescendingOrder:
            value: createdAt desc
            summary: sort data based on createdAt in descending order
          orderByUpdatedAtInAscendingOrder:
            value: updatedAt
            summary: sort data based on updatedAt in ascending order
          orderByUpdatedAtInDescendingOrder:
            value: updatedAt desc
            summary: sort data based on updatedAt in descending order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobPage'
              examples:
                default:
                  $ref: '#/components/examples/JobPageResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /accounts/{accountId}/communication-managers/{communicationManagerId}/jobs/{jobId}:abort:
    post:
      tags:
      - Comm Manager Job Details
      summary: Abort sync job execution
      description: '**This API requires the Account Administrator role.**


        Abort execution of a job by its job id.'
      operationId: abortJob
      parameters:
      - $ref: '#/components/parameters/accountId'
      - $ref: '#/components/parameters/communicationManagerId'
      - $ref: '#/components/parameters/jobId'
      responses:
        '202':
          description: Accepted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    SyncEntityData:
      type: object
      description: Details of sync entity data
      properties:
        id:
          type: string
          readOnly: true
        entityType:
          type: string
          enum:
          - AGENT
          - EXTENSION
          - REASONCODE
          - SYSTEM_PARAMETER_FEATURES
          readOnly: true
          description: Type of the entity
          example: AGENT
        entityData:
          $ref: '#/components/schemas/EntityData'
        createdAt:
          type: string
          readOnly: true
          format: date-time
          description: Specifies the date-time in UTC format when the job was created
          example: 2020-04-21T17:40:28z
        updateAt:
          type: string
          readOnly: true
          format: date-time
          description: Specifies the date-time in UTC format when the job was created
          example: 2020-04-21T17:42:28z
        statusCode:
          type: string
          description: Status of sync entity
          enum:
          - COMPLETED
          - FAILED
          - IN_PROGRESS
          - CREATED
          - UPDATED
          - DELETED
          - CREATE_IN_PROGRESS
          - UPDATE_IN_PROGRESS
          - NEEDS_ACTION
          example: COMPLETED
        statusMessage:
          type: string
          description: Message status of sync entity
          example: Successfully synced
    ExtensionSyncData:
      type: object
      properties:
        name:
          type: string
          description: Name of extention
          example: extention002
        number:
          type: string
          description: Number assigned to extention
          example: '102'
    Links:
      type: object
      properties:
        prev:
          type: string
          description: URL of the previous page. Blank if currently on the first page.
        next:
          type: string
          description: URL of the next page. Blank if currently on the last page.
    ReasonCodeSyncData:
      type: object
      properties:
        name:
          type: string
          description: Name of reason code
          example: rc001
        number:
          type: string
          description: Number of the reason code
          example: '1'
    AgentSyncData:
      type: object
      properties:
        name:
          type: string
          description: Name of agent
          example: agent001
        number:
          type: string
          description: Number assigned to agent
          example: '101'
        loginId:
          type: string
          description: Login Id of the associated user
          example: user@avaya.com
    SyncEntityDetails:
      type: object
      properties:
        entityCount:
          type: integer
          format: int64
          description: The total number of objects of an entity received in job response
          example: 20
        statusCode:
          type: string
          description: Status of the job entity
          enum:
          - IN_PROGRESS
          - FAILED
          - COMPLETED
          - CREATED
          - UPDATED
          - DELETED
          - CREATE_IN_PROGRESS
          - UPDATE_IN_PROGRESS
          - NEEDS_ACTION
          example: COMPLETED
        statusMessage:
          type: string
          description: Success or Failure message of the job entity
          example: Synchronization completed
    Job:
      type: object
      description: Details of a single job
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: fa703a3a-3dfb-4606-ae79-fd0fe0be3e64
          description: The unique id of the job.
        name:
          type: string
          example: FullSync_SYNC_Mon Feb 27 10:13:22 GMT 2023
          description: The name of the job. If not provided, job name is set using pattern 'FullSync_{JOBTYPE}_{GMT_DateTime}'
        type:
          type: string
          description: The type of job.
          enum:
          - SYNC
          - INCREMENTAL_SYNC
          example: SYNC
        statusCode:
          type: string
          description: Status code of the job
          enum:
          - QUEUED
          - IN_PROGRESS
          - COMPLETED
          - TIMEOUT_FAILED
          - FAILED
          - NEEDS_ACTION
          example: IN_PROGRESS
        statusMessage:
          type: string
          description: Success or Failure message of job
          example: Synchronization completed
        createdAt:
          type: string
          readOnly: true
          format: date-time
          description: Specifies the date-time in UTC format when the job was created
          example: 2020-04-21T17:40:28z
        updatedAt:
          type: string
          readOnly: true
          format: date-time
          description: Specifies the date-time in UTC format when the job was last updated
          example: 2020-04-21T17:40:28z
    SystemParameterFeaturesSyncData:
      type: object
      properties:
        name:
          type: string
          description: Name of system parameter feature
          example: auxWorkResonCodeType
        value:
          type: string
          description: value of System parameter feature
          example: forced
    JobEntityDetails:
      type: object
      description: Details of the entities pertaining to a job
      properties:
        entityType:
          type: string
          enum:
          - AGENT
          - EXTENSION
          - VDN
          - REASONCODE_AUX
          - REASONCODE_LOGOUT
          - SYSTEM_PARAMETER_FEATURES
          description: Name of job entity
          example: AGENT
        entityStatus:
          type: string
          enum:
          - COMPLETED
          - FAILED
          - IN_PROGRESS
          - CREATED
          - UPDATED
          - DELETED
          - CREATE_IN_PROGRESS
          - UPDATE_IN_PROGRESS
          - DELETE_IN_PROGRESS
          - NEEDS_ACTION
          description: Status of job entity
          example: COMPLETED
        entitySyncDetails:
          type: array
          items:
            $ref: '#/components/schemas/SyncEntityDetails'
    JobDetails:
      type: object
      description: Details of a single job
      properties:
        jobEntityDetails:
          type: array
          items:
            $ref: '#/components/schemas/JobEntityDetails'
    Pagination:
      type: object
      properties:
        pageNumber:
          type: integer
          description: The current page number.
        pageSize:
          type: integer
          description: The max number of records that can be retrieved on this page.
        total:
          type: integer
          description: The total number of records.
    EntityData:
      type: object
      description: details for entity data
      properties:
        agent:
          $ref: '#/components/schemas/AgentSyncData'
        extension:
          $ref: '#/components/schemas/ExtensionSyncData'
        reasonCode:
          $ref: '#/components/schemas/ReasonCodeSyncData'
        systemParameterFeatures:
          $ref: '#/components/schemas/SystemParameterFeaturesSyncData'
    JobPage:
      type: object
      description: List of jobs for the Communication Manager
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/Job'
        links:
          allOf:
          - $ref: '#/components/schemas/Links'
          example:
            prev: /api/admin/voice/v1/accounts/ASDJGE/communication-managers/a4c2c9b5-0e47-491d-b139-dc48cccdea72/jobs?pageNumber=1&pageSize=10
            next: /api/admin/voice/v1/accounts/ASDJGE/communication-managers/a4c2c9b5-0e47-491d-b139-dc48cccdea72/jobs?pageNumber=3&pageSize=10
    SyncEntityDetailsPage:
      type: object
      description: List of sync entity details data
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        syncEntityDetails:
          type: array
          items:
            $ref: '#/components/schemas/SyncEntityData'
        links:
          allOf:
          - $ref: '#/components/schemas/Links'
          example:
            prev: /api/admin/voice/v1/accounts/ASDJGE/communication-managers/a4c2c9b5-0e47-491d-b139-dc48cccdea72/jobs?entityType=AGENT&pageNumber=1&pageSize=10
            next: /api/admin/voice/v1/accounts/ASDJGE/communication-managers/a4c2c9b5-0e47-491d-b139-dc48cccdea72/jobs?entityType=AGENTpageNumber=3&pageSize=10
    Problem:
      type: object
      description: '<b>Problem Detail</b> as a way to carry machine-readable details of errors in a HTTP response to avoid the need to define new error response formats for HTTP APIs <a href="https://tools.ietf.org/html/rfc7807">RFC 7807</a>

        '
      properties:
        type:
          type: string
          format: uri
          description: 'An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).

            '
          default: about:blank
          example: https://developers.avayacloud.com/onecloud-ccaas/docs/error-handling#constraint-violation
        title:
          type:
          - string
          - 'null'
          description: 'A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized).

            '
          example: Service Unavailable
        status:
          type:
          - integer
          - 'null'
          format: int32
          description: 'The HTTP status code generated by the origin server for this occurrence of the problem.

            '
          minimum: 100
          example: 503
          exclusiveMaximum: 600
        detail:
          type:
          - string
          - 'null'
          description: 'A human readable explanation specific to this occurrence of the problem.

            '
          example: Connection to database timed out
        instance:
          type:
          - string
          - 'null'
          format: uri
          description: 'An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.

            '
        violations:
          type:
          - array
          - 'null'
          description: 'A list of violations that occurred as a result of invalid data provided as part of a request.

            '
          items:
            type: object
            properties:
              field:
                type: string
                description: 'The name of the field in the request that caused the violation. This can be the name of a path parameter, query parameter, or a field within the request body.

                  '
                example: accountId
              message:
                type: string
                description: 'A human readable explanation specific to this occurrence of the violation.

                  '
                example: must match "^[a-zA-Z]{6}$"
              code:
                type: integer
                format: int32
                description: 'The violation code generated by the server for this occurrence of the violation. Use this code when implementing any error handling logic instead of the message, as the message can change.

                  '
                example: 20006
          example:
          - field: emailAddress
            message: must not be null
            code: 20002
          - field: accountId
            message: must match "^[a-zA-Z]{6}$"
            code: 20006
  examples:
    ErrorForbidden:
      description: Forbidden
      value:
        type: https://developers.avayacloud.com/onecloud-ccaas/docs/error-handling#forbidden
        title: Forbidden
        status: 403
        detail: According to the access control policy the current user does not have permission to access this resource.
    JobDetailsResponse:
      description: Details of a single job
      value:
        jobEntityDetails:
        - entityType: AGENT
          entityStatus: COMPLETED
          entitySyncDetails:
          - entityCount: 20
            statusCode: COMPLETED
            statusMessage: Synchronization completed successfully
          - entityCount: 2
            statusCode: FAILED
            statusMessage: Synchronization failed because of incorrect domain name.
          - entityCount: 5
            statusCode: IN_PROGRESS
            statusMessage: Synchronization is in progress.
          - entityCount: 5
            statusCode: CREATED
            statusMessage: Synchronization completed successfully
          - entityCount: 5
            statusCode: UPDATED
            statusMessage: Synchronization completed successfully
          - entityCount: 5
            statusCode: CREATE_IN_PROGRESS
            statusMessage: Synchronization create is in progress.
          - entityCount: 5
            statusCode: UPDATE_IN_PROGRESS
            statusMessage: Synchronization update is in progress.
          - entityCount: 5
            statusCode: DELETED
            statusMessage: Synchronization completed successfully
          - entityCount: 5
            statusCode: NEEDS_ACTION
            statusMessage: Synchronization needs action.
    ErrorMethodNotAllowed:
      description: Method not allowed
      value:
        title: Method not allowed
        status: 405
        detail: The request calls an HTTP method that is not supported at the resource.
    SyncEntityDetailsResponse:
      description: Details of a sync entity data
      value:
        pagination:
          pageNumber: 2
          pageSize: 2
          total: 3
        syncEntityDetails:
        - id: fa703a3a-3dfb-4606-ae79-fd0fe0df3e64
          createdAt: 2020-04-21T17:40:28z
          updateAt: 2020-04-21T17:40:29z
          entityType: AGENT
          entityData:
            agent:
              name: agent101
              number: '101'
              loginId: user@avaya.com
          statusCode: COMPLETED
          statusMessage: Synchronized successfully
        - id: pk703a3a-3dfb-4606-ae79-fd0fe0be3e98
          createdAt: 2020-04-21T17:40:45z
          updateAt: 2020-04-21T17:40:56z
          entityType: AGENT
          entityData:
            agent:
              name: agent101
              number: '101'
              loginId: user@avaya.com
          statusCode: COMPLETED
          statusMessage: Synchronized successfully
        links:
          prev: /api/admin/voice/v1/accounts/ASDJGE/communication-managers/a4c2c9b5-0e47-491d-b139-dc48cccdea72/jobs?entityType?AGENT&pageNumber=1&pageSize=2
          next: /api/admin/voice/v1/accounts/ASDJGE/communication-managers/a4c2c9b5-0e47-491d-b139-dc48cccdea72/jobs?entityType?AGENT&pageNumber=3&pageSize=2
    ErrorNotFound:
      description: Not Found
      value:
        type: https://developers.avayacloud.com/onecloud-ccaas/docs/error-handling#resource-not-found
        title: Resource Not Found
        status: 404
        detail: Either there is no API method associated with the URL path of the request, or the request refers to one or more resources that were not found.
    ErrorUnauthorized:
      description: Unauthorized
      value:
        type: https://developers.avayacloud.com/onecloud-ccaas/docs/error-handling#unauthorized
        title: Unauthorized
        status: 401
        detail: This operation requires authentication. See https://developers.avayacloud.com/onecloud-ccaas/docs/how-to-authenticate-with-ccaas-apis
    JobPageResponse:
      description: Jobs List Example
      value:
        pagination:
          pageNumber: 2
          pageSize: 2
          total: 3
        jobs:
        - id: 18e4f754-5e42-4387-ae13-e9b4fe4aed29
          name: FullSync_SYNC_Mon Feb 27 10:13:22 GMT 2023
          type: SYNC
          statusCode: COMPLETED
          statusMessage: Synchronization completed
          createdAt: 2020-04-21T17:40:28z
          updatedAt: 2020-04-21T18:30:28z
        links:
          prev: /api/admin/v1/accounts/ASDJGE/communication-managers/a4c2c9b5-0e47-491d-b139-dc48cccdea72/jobs?pageNumber=1&pageSize=2
          next: /api/admin/v1/accounts/ASDJGE/communication-managers/a4c2c9b5-0e47-491d-b139-dc48cccdea72/jobs?pageNumber=3&pageSize=2
    JobResponse:
      description: Single job response
      value:
        id: 18e4f754-5e42-4387-ae13-e9b4fe4aed29
        name: FullSync_SYNC_Mon Feb 27 10:13:22 GMT 2023
        type: SYNC
        statusCode: COMPLETED
        statusMessage: Synchronization completed
        createdAt: 2020-04-21T17:40:28z
        updatedAt: 2020-04-21T18:30:28z
    ErrorInternalServerError:
      description: Server Error
      value:
        type: https://developers.avayacloud.com/onecloud-ccaas/docs/error-handling#server-error
        title: Server Error
        status: 500
        detail: An internal server error was encountered.
  responses:
    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            default:
              $ref: '#/components/examples/ErrorNotFound'
    InternalServerError:
      description: All other application errors
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            default:
              $ref: '#/components/examples/ErrorInternalServerError'
    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            default:
              $ref: '#/components/examples/ErrorForbidden'
    MethodNotAllowed:
      description: Method Not Allowed
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            default:
              $ref: '#/components/examples/ErrorMethodNotAllowed'
    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            default:
              $ref: '#/components/examples/ErrorUnauthorized'
  parameters:
    accountId:
      name: accountId
      description: The unique 6 character internal id that represents the customer account.
      required: true
      in: path
      schema:
        type: string
        minLength: 6
        maxLength: 6
        pattern: ^[a-zA-Z]{6}$
        example: ABCDEF
    jobId:
      name: jobId
      in: path
      description: The unique 36 character internal id of the Job
      required: true
      schema:
        type: string
        format: uuid
        example: a4c2c9b5-0e47-491d-b139-dc48cccdea72
    pageNumber:
      name: pageNumber
      in: query
      description: The page number of the records to retrieve. Default value is 1.
      required: false
      schema:
        type: integer
        format: int32
        example: 1
        default: 1
        minimum: 1
    communicationManagerId:
      name: communicationManagerId
      description: The unique id of the Communication Manager
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 2ec20580-d204-43f3-ae0b-34795439137f
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: This API uses Bearer Token Authorization Flow
      bearerFormat: JWT
    AppKey:
      type: apiKey
      in: header
      name: appkey
      description: This API needs an appKey as header
x-explorer-enabled: false
x-samples-languages:
- curl
- node
- java
- javascript
- python
- go
